spring:
  application:
    name: robot-virtual-environment

openapi:
  robot:
    base-path: /robot

default:
  environment:
    width: 5
    height: 5
  robot:
    location:
      xCoordinate: 0
      yCoordinate: 0
    direction: SOUTH
