spring:
  application:
    name: robot-virtual-environment

server:
  servlet:
    context-path: /robot

default:
  environment:
    width: 4
    height: 4
  robot:
    location:
      xCoordinate:
        min: 0
        max: 1000
        default-value: 0
      yCoordinate:
        min: 0
        max: 1000
        default-value: 0
    direction: EAST
    script:
      commands:
        max: 1000
      steps:
        min: -999
        max: 999
