spring:
  application:
    name: robot-virtual-environment

openapi:
  robot:
    base-path: /robot

default:
  environment:
    width:
      min: 0
      max: 1000
      default-value: 5
    height:
      min: 0
      max: 1000
      default-value: 5
  robot:
    location:
      xCoordinate:
        min: 0
        max: 1000
        default-value: 0
      yCoordinate:
        min: 0
        max: 1000
        default-value: 0
    direction: SOUTH
    script:
      commands:
        min: 0
        max: 1000
      steps:
        min: -1000
        max: 1000
