spring:
  # TODO remove after tests
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  application:
    name: robot-virtual-environment
  # TODO remove after tests
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0

server:
  servlet:
    context-path: /robot

default:
  environment:
    width: 4
    height: 4
  robot:
    location:
      xCoordinate:
        min: 0
        max: 1000
        default-value: 0
      yCoordinate:
        min: 0
        max: 1000
        default-value: 0
    direction: EAST
    script:
      commands:
        max: 1000
      steps:
        min: -999
        max: 999
